### ISSUE TITLE
Hyphen separator for accents?

### ISSUE THREAD

**Issue by jackjennings** [LettError/glyphNameFormatter#1]
Looking through the glyph list, I wonder if it's worth adding a hyphen to separate the accent from the base glyph, e.g. `Schwa-dieresis` rather than `Schwadieresis`?

`aacute` and friends are relatively easy to discern (and I think that we're used to setting that format), but the non-latin letters that have names spelled out get much harder to parse.

**Comment by LettError** [comment]
Keep in mind that familiarity with existing names does not make them necessarily better. Part of the exercise is to see if there are more consistent ways to solve all of them.

Adding the script to disambiguate `a` from `a-cyr` is a possibility but it adds a latin-centric logic. The names I've seen from Glyphs appear to use the hyphen exclusively for these kinds of script tags. 

`Eclosedreversedsmallopen` there is not very much to improve on it?

**Comment by LettError** [comment]
Do you know if it is possible to include a file from a different repository?

**Comment by LettError** [comment]
There are too many accents to do this in a consistent and reliable manner. We do implement hyphens when adding script extensions.

**Comment by davelab6** [comment]
> Do you know if it is possible to include a file from a different repository?

http://git-scm.com/book/en/v2/Git-Tools-Advanced-Merging#_subtree_merge
