### ISSUE TITLE
Dash, prefixes, suffixes, and a few other questions

### ISSUE THREAD

**Issue by twardoch** [LettError/glyphNameFormatter#10]
Hi, 
I wonder, could you perhaps clarify: Is there a particular reason (other than just a "decision" :) ) that you’ve decided to put the "script" components as prefixes (while Glyphs uses suffixes). I'm myself rather undecided on that. :) 

A.

**Comment by typemytype** [comment]
1. creating a separate issue for this one see https://github.com/LettError/glyphNameFormatter/issues/11

2. first some CY char got a pre/suffix on a glyph by glyph base, a long the way we changed our minds and shifted to a range related pre/suffix

3. script can be either extend at the end of beginning, see https://github.com/LettError/glyphNameFormatter/blob/master/Lib/glyphNameFormatter/data/scriptPrefixes.py#L52
as default it prefixes 

4. also creating a separate issue for the double cmb- naming see https://github.com/LettError/glyphNameFormatter/issues/12

**Comment by LettError** [comment]
I have a fix for #2

**Comment by twardoch** [comment]
Sorry :) I just redid the issue and put the "cyrcyr" into a separate issue as well. I know, it's not good to aggregate unrelated issues into one.
