### ISSUE TITLE
License Question

### ISSUE THREAD

**Issue by MartinThoma** [LettError/glyphNameFormatter#103]
Hiho :-) 

I've just seen a PR to PyPDF2 which I would like to merge:
https://github.com/py-pdf/PyPDF2/pull/464/files#diff-ce741630626352a9aed9ccea85afcdab2ea97c1a7d705f1542ee4b989783f2b0

However, I'm uncertain if that is ok from a copyright perspective. The generated file contains a link to glyphNameFormatter, but not the copyright notice. I guess we should add the copyright notice to the top of the file?

**Comment by LettError** [comment]
I don't see which file you mention, but if it references GlyphNameFormatter it should contain a link to this repository.

**Comment by MartinThoma** [comment]
@LettError I've created another PR which extends the file `_adobe_glyphs.py` by data from glyphNameFormatter: https://github.com/py-pdf/PyPDF2/pull/947/files

I've added this comment on the top of that file:

```
# Extended with data from GlyphNameFormatter:
#    https://github.com/LettError/glyphNameFormatter
```

Does that look ok?

**Comment by MartinThoma** [comment]
Thank you - I'll take that :+1: as "it's ok" :-)
