### ISSUE TITLE
double cmb

### ISSUE THREAD

**Issue by typemytype** [LettError/glyphNameFormatter#12]
For combining marks, I myself was thinking about using something like grave.mark or grave:mark. I see you’ve used the cmb- prefix. If so, would you say that perhaps the comb suffixes could be dropped from some? Right now it's:

```
cmb-gravecomb 0300
cmb-tildecomb 0303
cmb-macron 0304
```

but perhaps it'd make sense to just make it:

```
cmb-grave 0300
cmb-tilde 0303
cmb-macron 0304
```

**Comment by typemytype** [comment]
Those still follow the AGL 
 https://github.com/LettError/glyphNameFormatter/blob/master/Lib/glyphNameFormatter/data/preferredAGLNames.py#L20-L24

**Comment by LettError** [comment]
I noticed `combining_diacritical_marks_supplement.py` also needs the prefix. I like the idea of keeping the combining things together, I would be in favor of the change proposed by Adam.
