### ISSUE TITLE
"Generating" script and variation abbreviations

### ISSUE THREAD

**Issue by twardoch** [LettError/glyphNameFormatter#14]
I think it would make sense to utilize the OpenType [script tags](https://www.microsoft.com/typography/otspec/scripttags.htm) and [feature tags](https://www.microsoft.com/typography/otspec/featurelist.htm) as much as possible when generating script and variation names. The most common scripts should indeed have a supershort (2-char) abbreviations, for others we could use the 4-letter ones. 

For example when I look at [the halfwidth and fullwidth](https://github.com/LettError/glyphNameFormatter/blob/master/Lib/glyphNameFormatter/names/ranges/names_halfwidth_and_fullwidth_forms.txt) names, I think: there are two OT features, `hwid` for "Half Widths" and `fwid` for "Full Widths". So I imagine `FF21  Afullwidth  FULLWIDTH LATIN CAPITAL LETTER A` becoming `A:fwid` and `FF8C   hlfw-huhalfwidth    HALFWIDTH KATAKANA LETTER HU` becoming `hu:hwid` or `hwid:hu` (if we choose to adopt `:`). 

Also, Gurmukhi in OT uses `guru` while [our list](https://github.com/LettError/glyphNameFormatter/blob/master/Lib/glyphNameFormatter/names/ranges/names_gurmukhi.txt) uses `grmk`. So I can imagine `0A22   grmk-ddha   GURMUKHI LETTER DDHA` becoming `ddha:guru` or `guru:ddha`. 

I'm off for the weekend teaching, but I'll be back next week and will try to do some more systematic work on this. After more deliberation, I think prefixes are better than suffixes for scripts. :D

**Comment by LettError** [comment]
I like the idea of using `:` for separating the parts.

**Comment by schriftgestalt** [comment]
> After more deliberation, I think prefixes are better than suffixes for scripts. :D

I don’t agree. As I think it is not as readable. There are better ways to sort glyph, so it is not needed for that.

**Comment by davelab6** [comment]
> There are better ways to sort glyph, so it is not needed for that.

I just mentioned sorting order as a reason to prefix... please could you elaborate on this? :)

**Comment by LettError** [comment]
Sorting with prefixes would group names with the same prefix. However, prefixes don't precisely map to unicode ranges. There are ranges with multiple scripts, there are scripts that run over multiple ranges.

**Comment by schriftgestalt** [comment]
I think there are several reasons. 

First and most important: sorting anything by glyph name does not produce a useable result. That has actually nothing to do with the script. Yes, you would have all glyph from one script together, but in everything else is messed up. For most scripts you need to sort by unicode or sometimes even manually set ordering. 

preferred order:
```
	zero
	one
	two
	three
	four
	five
	six
	seven
	eight
	nine
```
alphabetic:
```
	eight
	five
	four
	nine
	one
	seven
	six
	three
	two
	zero
```

So to sort glyphs, you need metadata and that metadata is much better at separating the glyphs in categories and scripts.

Second: Readability
here is two list of random thai glyph names

Prefix | Suffix
--- | ---
koKai-thai.alt | thai-koKai.alt 
thoThung-thai| thai-thoThung
ru-thai.alt | thai-ru.alt 
lu-thai.alt | thai-lu.alt 
soSo-thai | thai-soSo 
khoKhwai-thai| thai-khoKhwai
khoKhon-thai | thai-khoKhon 
soSala-thai | thai-soSala 
doDek-thai.alt | thai-doDek.alt 
toTao-thai | thai-toTao 
noNu-thai | thai-noNu 
moMa-thai.alt | thai-moMa.alt 
choChoe-thai | thai-choChoe 
noNen-thai | thai-noNen 
thoThong-thai| thai-thoThong
roRua-thai.alt | thai-roRua.alt 
loLing-thai | thai-loLing 
soSua-thai.alt | thai-soSua.alt 
boBaimai-thai | thai-boBaimai

And I think it is easier to find a name in the left column. Especially the names with an extra suffix have the actual glyph name crowded on both sides.

Third: typing with autocomplete
If you type in a text field or text view that has autocomplete, you always have to type the full prefix before the autocomplete mechanism can help you. In a font with some indic scripts, you need to type `ka` and it will present you with a reasonable long list of options. 

Fourth: Labels in UI
Names tend to be longer than the available space in UI e.g. in grid view. So the name needs to be truncated. MacOS provides three options (and I can’t think of a different solutions): Truncate tail, truncate middle and truncate head. lets consider a name like `seen_jeem-ar.init.alt`. What is the most important parts: that it is a seen_jeem ligature. Then that it is an initial shape, then that it is an alternate. If the name is written as above, a middle truncation would produce something like `seen_j..init.alt`. Not nice but you can get it. With a prefix it would look like this: `ar-see..init.alt`.

Truncating head and tail is much worse in any case.

**Comment by LettError** [comment]
* I think UI issues are out of scope. Some of these names are going to be impractically long no matter which prefixing scheme is used. 

* autocomplete: interesting argument, but by the same token text shortcuts can be programmed to add prefixes after a name has been typed. 

* `doDek-thai.alt` is an example against suffixing, IMO. The `thai` and `.alt` are completely different orders of information, the further they are apart the better.

**Comment by schriftgestalt** [comment]
> I think UI issues are out of scope. Some of these names are going to be impractically long no matter which prefixing scheme is used.

This argument suggests to put the most important parts at the beginning and then end. The script is not that important. Name and suffix is more important.

> autocomplete: interesting argument, but by the same token text shortcuts can be programmed to add prefixes after a name has been typed.

But that would mean everybody would need to have a special implementation. 

> doDek-thai.alt is an example against suffixing, IMO. The thai and .alt are completely different orders of information, the further they are apart the better.

You mean we should order the parts by scope? So script is bigger than single glyph so it goes in front? Why not call it an annotation to the glyph name, then it would go behind.

**Comment by typemytype** [comment]
I think there should be a difference between user defined names like glyph names with an extension like `.alt` (in your example) which doesn't have a unicode and encoded glyphs. Those un-encoded glyphNames don't fit here and only makes sense for a specific user.

(A recommendation how users could extend glyph names could be specified.)

**Comment by schriftgestalt** [comment]
I know that the .alt names are not supposed to be in that list. But they happen and thous need to be considered to evaluate the usefulness and readability. And for some scripts you will have much more extra suffixes (e.g. Arabic)

**Comment by twardoch** [comment]
BTW, Microsoft announced that they will keep the Unicode [Scripts](http://www.unicode.org/Public/UCD/latest/ucd/Scripts.txt) list and the [OT script tags](https://www.microsoft.com/typography/otspec/scripttags.htm) in sync. Scripts aren’t added so often, so perhaps we might switch to a static list somehow, with custom additions?
