### ISSUE TITLE
Doubling separators to resolve ambiguities

### ISSUE THREAD

**Issue by twardoch** [LettError/glyphNameFormatter#15]
I'd like to suggest a simple algorithmic approach to resolve ambiguities in compound glyph names. 

Let's for now agree that our sxtended conventions for glyph name separators will be, on the decreasing order of strength (unlike the AGL rules where `.` is stronger than `_`): 
- use `_` to indicate constituents of a glyph that corresponds in some way to multiple glyphs or characters
- use `.` to indicate a split between “character” portion and “feature” portion
- use `:` as a categorizing separator within the character or feature portion

With this simple system, there will be a few edge cases where the hierarchy is ambiguous. I’d like to propose a simple solution — by repeating the separator, we increase its splitting priority. 

So, the name `f_f.fina` is a bit ambiguous as we’re not a 100% sure whether it represents something like `(f)_(f.fina)` or something like `(f_f).fina`. A simple way to resolve this ambiguity would be to use the name `f__f.fina` in the 1st case and `f_f..fina` in the 2nd. 

Another such case: `lam.medi_alif.init.ss01` is a bit ambiguous but `lam.medi_alif.init..ss01` = `(lam.medi_alif.init.)ss01` while `lam.medi__alif.init.ss01` = `(lam.medi)_(alif.init.ss01)`. 

This suggestion is a bit out of scope for this project, but I'd like to hear your thoughts about it as a guiding principle.

**Comment by twardoch** [comment]
Following this, `cmb:dieresis_cmb:acute` would be equivalent to, and possibly more efficiently expressed as`cmb::dieresis_acute`.

**Comment by schriftgestalt** [comment]
There is a much easer solution for the ligature+suffix problem. If there is a suffix like ss01 then it counts for the ligatures as a hole, to describe suffixed for individual parts, use (the same number of) underscores. So f + f.ss01 would be f_f._ss01, f.titl + f.sc would be f_f.titl_sc.
