### ISSUE TITLE
"Radical" thought: "+"

### ISSUE THREAD

**Issue by twardoch** [LettError/glyphNameFormatter#16]
Here's a more radical idea. FDK now also allows `+` in glyph names. So I recently thought — wouldn’t it be simplest to ditch the AGL names like `Aacute` and consistently use `A+acute`? The `+` could be the replacement of the Unicode character name term `WITH`. And the non-spacing marks could be renamed `+acute`, `+grave` etc. (instead of `cmb-*`). 

Ok, it is a bit radical but... who knows.

**Comment by LettError** [comment]
`WITH` is also used in ligatures and double accents.

**Comment by twardoch** [comment]
Hm. :/
