### ISSUE TITLE
Names should only have script- prefix for disambiguation

### ISSUE THREAD

**Issue by LettError** [LettError/glyphNameFormatter#2]
All names are generated with script prefixes if they have one defined. It should only be used if there is a conflict with another letter.

**Comment by LettError** [comment]
Hebrew names should preferably have a -hb extension for all names, not just the interscript-conflicts.

**Comment by LettError** [comment]
This issue is addressed in the current release. We'll see how it works out.

**Comment by schriftgestalt** [comment]
I would suggest to add a script tag for all glyphs of a script even if there are only a few conflicting glyphs. Otherwise it is to confusing. And for the most parts, only Greek didn’t need a script tag in my lists. And for the more unknown scripts it might make sense to add them even if there are no conflicts, just to make it easier to understand.

**Comment by LettError** [comment]
I tried adding the script to the name only in the case of conflicts as that would spread the responsibility among scripts. 
* Historically the naming has been very latin centric, and I thought that perhaps shorter names would be welcome. 
* I've spoken to stakeholders for Cyrillic and Hebrew names and they told me script extensions for the whole range is better than just the conflicts.
* Only tagging the conflicts also could bring changes to names that are not in conflict now, but could be in the future. 

So these point towards tagging whole ranges. The next question is then:
* Should Latin and Greek be tagged as well?

**Comment by schriftgestalt** [comment]
Latin is a bit of an exception. It is the basis of how computers works and changing its names would break to many things. And greek names are fine and the polytonic names are already quite long.

I added a few "-latin" suffixes in my names (alpha-latin, uni0251). So there are a few exemptions from the "Tag one, tag all rule".

**Comment by typemytype** [comment]
see https://github.com/LettError/glyphNameFormatter/blob/master/Lib/glyphNameFormatter/names/glyphNamesToUnicode.txt#L6299 

and see https://github.com/LettError/glyphNameFormatter/blob/master/Lib/glyphNameFormatter/rangeProcessors/latin_extended_b.py#L36-L38

all latin greek unicode points have a latin pre/suffix

**Comment by schriftgestalt** [comment]
I was just explaining how I do it. Happy that we agree on this.

Can we decide to use a prefix or suffix, not both? I’m in favor of suffix as the script is more of an extra information and the name should start with the most significant part.
