### ISSUE TITLE
Arabic naming: fullstop

### ISSUE THREAD

**Issue by LettError** [LettError/glyphNameFormatter#22]
`06D4	ar-period	ARABIC FULL STOP`
`06D4	fullstop	ARABIC FULL STOP`
this is not a generic arabic stop. It’s only used in Urdu. Calling it arabic period would be confusing.

**Comment by LettError** [comment]
Fixed

**Comment by davelab6** [comment]
I see this is now `periodurdu` but there is another 'fullstop' for Ethiopic; should that be 'period'?
