### ISSUE TITLE
Arabic naming: yehhamzaabove.medi_alef.fina

### ISSUE THREAD

**Issue by LettError** [LettError/glyphNameFormatter#27]
`FBEA   yeh.init_hamzaabove.medi_alef.fina  ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH ALEF ISOLATED FORM`
`FBEA   yehhamzaabove.medi_alef.fina    ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH ALEF ISOLATED FORM`

hamzaabove is a diacritic so it’s part of the letter “U+0626”. I guess before making the ligature you could check if any two components combined are a letter, so instead of treating them as two components just add the letter if its name exist in database. (there are many more examples like this in ligatures.)

**Comment by LettError** [comment]
Raised by @typoman

**Comment by twardoch** [comment]
This is a case where using decomposition might be better. The decomposition rule for U+FBEA (ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH ALEF ISOLATED FORM) is `<isolated> 0626 0627`, and the constituents are: 
* U+0626 (ARABIC LETTER YEH WITH HAMZA ABOVE /yehhamza — /yehhamzaabove would be better) which in turn decomposes into
  * U+064A (ARABIC LETTER YEH /yeh) 
  * U+0654 (ARABIC HAMZA ABOVE /hamzaabove)
* U+0627 (ARABIC LETTER ALEF /ar:alef — here the prefix seems unneeded)

If we go by the decomposition, we could extract the constituents i.e. /yehhamzaabove and /alef, merge them with "_" to get /yehhamzaabove_alef and then apply the suffix, which could result either in /yehhamzaabove_alef.isol or (if we go by my idea of [doubling separators](https://github.com/LettError/glyphNameFormatter/issues/15)) in /yehhamzaabove_alef..isol

**Comment by LettError** [comment]
U+0627 (ARABIC LETTER ALEF /ar:alef — here the prefix seems unneeded)
I think that prefix happens to disambiguate from the Hebrew `alef-hb 05D0`.
