### ISSUE TITLE
conflict in halfforms

### ISSUE THREAD

**Issue by typemytype** [LettError/glyphNameFormatter#30]
```
hlfw-ahalfwidth                         Halfwidth and Fullwidth Forms           HALFWIDTH KATAKANA LETTER A
hlfw-ahalfwidth                         Halfwidth and Fullwidth Forms           HALFWIDTH HANGUL LETTER A
```
add script tag for each sub range 

there are more doubles:

```
    hlfw-ahalfwidth
    hlfw-ehalfwidth
    hlfw-ihalfwidth
    hlfw-ohalfwidth
    hlfw-uhalfwidth
    hlfw-wahalfwidth
    hlfw-yahalfwidth
    hlfw-yohalfwidth
    hlfw-yuhalfwidth
```

**Comment by LettError** [comment]
It would be great if each sub-range could be processed by their main script processor. There are a lot of names in this range that are already handled. Would be a waste to duplicate the effort.

* prefix of the sub-range, Latin, Katakana and Hangul + suffix halfwidth, fullwidth
or
* prefix halfwidth / fullwidth, + suffix for Latin, Katakana and Hangul

**Comment by LettError** [comment]
Fixed
