### ISSUE TITLE
preferred spelling guillemot <-> guillemet

### ISSUE THREAD

**Issue by typemytype** [LettError/glyphNameFormatter#37]
https://github.com/LettError/glyphNameFormatter/blob/master/Lib/glyphNameFormatter/rangeProcessors/latin_1_supplement.py#L38-L39

a collection of preferred spelling could be handy, now only dieresis is there, I guess there will be more

https://github.com/LettError/glyphNameFormatter/blob/master/Lib/glyphNameFormatter/__init__.py#L31

**Comment by LettError** [comment]
It could be a dictionary, but it would not automatically apply to everything, right? The diaeresis pref is used in a range processor only when necessary..

**Comment by adrientetar** [comment]
For reference, it seems "guillemot" is an old Adobe typo.
https://twitter.com/typenerd1/status/724677953657790466

**Comment by LettError** [comment]
Can this be closed?
