### ISSUE TITLE
PROSGEGRAMMENI and YPOGEGRAMMENI

### ISSUE THREAD

**Issue by twardoch** [LettError/glyphNameFormatter#38]
The issue with PROSGEGRAMMENI and YPOGEGRAMMENI is a bit complicated, and I won’t go into detail why but the recommended solution is: 
The character U+1FBE (GREEK PROSGEGRAMMENI) should be named `iotaadscript` as per AGD (alternatively `iotasmall`) while in all other contexts, the strings `YPOGEGRAMMENI` and `PROSGEGRAMMENI` should be converted to `iotasub`. Not sure how to do this in the [converter](https://github.com/LettError/glyphNameFormatter/blob/master/Lib/glyphNameFormatter/rangeProcessors/helper_greek_diacritics.py).

Currently, some become `iotasub` and others `iotasubscript` (and there's the "and" left): 
```
alphalenisandiotasubscript 1F80
alphaasperandiotasubscript 1F81
Alphalenisiotasub 1F88
Alphaasperiotasub 1F89
```

**Comment by LettError** [comment]
`iotaadscript 1FBE`

`alphalenisiotasub 1F80`
`alphaasperiotasub 1F81`
`Alphalenisiotasub 1F88`
`Alphaasperiotasub 1F89`

`etagraveiotasub 1FC2`
`etaiotasub 1FC3`
`etaacuteiotasub 1FC4`
etc.
