### ISSUE TITLE
Better unicodedata

### ISSUE THREAD

**Issue by twardoch** [LettError/glyphNameFormatter#40]
Erik, Frederik, 

the UCD (Unicode Character Database) contains a number of useful properties that we could use to improve the autonaming scheme. For example, there is the [`Math` property](http://www.unicode.org/Public/UCD/latest/ucd/DerivedCoreProperties.txt) which could be used to generate a `math:` prefix consistently. Also, for building certain glyph names, using the canonical decomposition might turn out to be easier than using the charname replacements. 
- [unicodedata2](https://github.com/mikekap/unicodedata2): Fast C++ Python 2.7-compatible `unicodedata` replacement with Unicode 8.0 support, expected to be updated to 9.0 when it’s officially released (Apache2-licensed)
- [unicode_data](https://github.com/googlei18n/nototools/blob/master/nototools/unicode_data.py): pure-Python “bleeding-edge” `unicodedata` replacement (Apache2-licensed), which exposes additional properties via parsing more UCD files. 
  (Those two above could be [combined](https://github.com/googlei18n/nototools/issues/205)). 

There are also those two tools I found: 
- [unipropgen](https://github.com/anraku/Packages/blob/master/backrefs/tools/unipropgen.py): Unicode property table generator (MIT-licensed)
- [pyucd](https://github.com/ghewl/libucd/tree/master/bin/pyucd): quite complete parser for UnicodeData (LGPL/GPL-licensed)

**Comment by twardoch** [comment]
If we adopt nototools' `unicode_data`, then we could use this: 
https://github.com/twardoch/glyphNameFormatter/blob/master/Lib/glyphNameFormatter/data/scriptPrefixesCust.py

**Comment by LettError** [comment]
That backport is interesting. Not sure about adding dependencies yet.

**Comment by twardoch** [comment]
I agree that you're careful about adding "too many" dependencies. I've used the pyicu module in a number of cases but it's somewhat tedious to install cleanly. But unicodedata2 has a superbly low overhead, and the construct
```py
try: 
  import unicodedata2 as unicodedata
except ImportError: 
  import unicodedata
```
falls back gracefully. In Py3, the builtin `unicodedata` already uses Unicode 8.0.0, but in Py2, the builtin module is ancient, and this one makes it on par with the current released version (and is likely to get updated when 9.0.0 is out). BTW, my [suggestion](https://github.com/googlei18n/nototools/issues/205) to use the above construct in `nototools.unicode_data` has been merged now. 

As for `nototools.unicode_data`, I understand concerns about relying on it. But since it's maintained by googlei18n and used for rather similar purposes, one can assume that it'll continue to be maintained. It is essentially "just" a parser for the UCD which is better than `unicodedata[2]` as it exposes more properties. I think in the longer run, querying more UCD properties and then using some of them before reverting to UCharnames will give us better results and less need for manual cleanup. But this would require some code refactoring of course, so I understand why you're cautious. 

But the nice thing about `nototools.unicode_data` is that is uses the fast name lookup from `unicodedata[2]` and falls back to the slower parsing for post-8.0.0 additions. This is a decent implementation with a low overhead, much better than anything else I've seen, and I'd say "any font-related app" should use it (unless it uses something like ICU). 

Unicode 9.0 is slated to be released in June 2016, and I think as we built up glyphNameParser, it makes sense to "be prepared" for Unicode 9.0. :)

**Comment by typemytype** [comment]
Im also not sure about adding dependencies...

as it is now, unicodedata is not used anymore


gr Frederik
www.typemytype.com

**Comment by LettError** [comment]
Can this be closed?

**Comment by moyogo** [comment]
unicodedata is still used in https://github.com/LettError/glyphNameFormatter/blob/45857f97848d079dc92728301b5ae818abe6503f/Lib/glyphNameFormatter/__init__.py#L101 and in two tests in testFindArabDiacritics.py and testCoverage.py.

**Comment by LettError** [comment]
Oof, I missed this one. It would be great to be independent of the python unicodedata completely. I propose to add the bidi data to `data/flatUnicode.txt`. If I look at `ucd.all.flat.xml` where all the data comes from, there are two fields with bidi info: `Bidi_M` and `Bidi_C`. I'm guessing this data can be used to recreate `unicodedata.bidirectional()`, but this being unicode, there might be extra conditions and exceptions?
