### ISSUE TITLE
Vowel removal in scriptPrefixes.py

### ISSUE THREAD

**Issue by twardoch** [LettError/glyphNameFormatter#41]
[scriptPrefixes](https://github.com/LettError/glyphNameFormatter/blob/master/Lib/glyphNameFormatter/data/scriptPrefixes.py) has a curious bit: 
```py
        # remove all vowels
        key = [c for c in key if c not in "aeiou -"]
```
Is this really necessary? I’d really love if the [OT script tags](https://www.microsoft.com/typography/otspec/scripttags.htm) were used as they are (except if we override them). This vowel removal feels a bit over the top and may introduce inconsistencies.

**Comment by LettError** [comment]
That is only the last fallback. The OT script tags are the first place to look. 
```py
def loadScripTags():
    data = {}
    path = os.path.dirname(__file__)
    path = os.path.join(path, "scriptTags.html")
```

**Comment by twardoch** [comment]
Ah, OK, thanks :)
