### ISSUE TITLE
GlyphData

### ISSUE THREAD

**Issue by schriftgestalt** [LettError/glyphNameFormatter#44]
We have put glyph names that are used in Glyphs in a repository: https://github.com/schriftgestalt/GlyphsInfo

**Comment by LettError** [comment]
Interesting, thanks!

**Comment by twardoch** [comment]
Thanks Georg, this is great news!

**Comment by typemytype** [comment]
Georg, the xml seems not to be valid...
you are missing a closing > for the ATTLIST, line 14

**Comment by schriftgestalt** [comment]
Fixed it. Thanks
