### ISSUE TITLE
name: cedilla vs commaaccent

### ISSUE THREAD

**Issue by typemytype** [LettError/glyphNameFormatter#45]
for glyphs that don't have both: Scedilla, Scommaaccent and Tcedilla, Tcommaacent

should doest be renamed the cedilla to commaaccent?
All existing list (AGL, AGD and Georgs Glyphs list) change the cedilla to a commaaccent.

Historically this is maybe a nice...

```
Kcedilla                                          Kcommaaccent                  Kcommaaccent                  0136   Ķ    LATIN CAPITAL LETTER K WITH CEDILLA
kcedilla                                          kcommaaccent                  kcommaaccent                  0137   ķ    LATIN SMALL LETTER K WITH CEDILLA
Lcedilla                                          Lcommaaccent                  Lcommaaccent                  013B   Ļ    LATIN CAPITAL LETTER L WITH CEDILLA
lcedilla                                          lcommaaccent                  lcommaaccent                  013C   ļ    LATIN SMALL LETTER L WITH CEDILLA
Ncedilla                                          Ncommaaccent                  Ncommaaccent                  0145   Ņ    LATIN CAPITAL LETTER N WITH CEDILLA
ncedilla                                          ncommaaccent                  ncommaaccent                  0146   ņ    LATIN SMALL LETTER N WITH CEDILLA
Rcedilla                                          Rcommaaccent                  Rcommaaccent                  0156   Ŗ    LATIN CAPITAL LETTER R WITH CEDILLA
rcedilla                                          rcommaaccent                  rcommaaccent                  0157   ŗ    LATIN SMALL LETTER R WITH CEDILLA
```

**Comment by justvanrossum** [comment]
If one converts from unicode to glyph names, the commaaccent versions are the right ones (see AGD.txt). When going the other way, both names should work.

I'm looking at this from RF, which goes through `lib.tools.glyphList`, which in turn uses `glyphNamesToUnicode.txt`, which only contains the cedilla versions. That can't be right.

**Comment by typemytype** [comment]
the last revision of AGL points out that all commaaccent are assigned with a `uni<hex>` glyph name.
https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/agl.py#L88

AGD still uses commaaccent 

Im thinking of added those to [preferredAGLNames.py](https://github.com/LettError/glyphNameFormatter/blob/master/Lib/glyphNameFormatter/data/preferredAGLNames.py)

**Comment by justvanrossum** [comment]
I don't see how AGL is relevant here.

I'm confused as to how GNF works and what preferredAGLNames.py means to do. If you add the commaacent names there, but AGL these days prefers `uni<hex>` names, then at least this module is oddly named...

**Comment by twardoch** [comment]
The names in AGL were all supposed to be supported primarily by Adobe apps, e.g. for guessing Unicode codepoints in Acrobat if a Type 1 font was included. Adobe apps do recognize the "-commaaccent" but older versions of Mac OS X also relied on glyph names inside OpenType CFF fonts (preferring them over the `cmap` table), and the glyph list inside Mac OS X did not understand the "-commaaccent" (the glyphs like Tcommaaccent wouldn’t render at all inside ATSUI or CoreText apps). So Adobe decided to remove the "-commaaccent" names from AGL to discourage people from ever using them in shipping fonts. For final glyph names, I’d recommend sticking to the`uniXXXX` glyph naming scheme for the "-commaaccent" glyphs.

**Comment by lianghai** [comment]
If these glyph names are intended to provide visual guidelines, then characters that were named with “CEDILLA” but are actually preferred to have a below/above-base comma accent should indeed have a `*commaaccent` name, particularly because the two accents have been only partially disunified in Unicode and are in the midst of the extremely confusing language-specific preferences.

I was looking at the Unicode Core Spec’s Table 7-1, _Preferred Rendering of Cedilla versus Comma Below_ (page 290, version 12.0), and it doesn’t make much sense to me (see how “s” is in the Cedilla column but “t” is in the Comma Below column?). If you guys have some clearer way to describe this matter, please consider submitting a proposal or feedback to UTC.

<img width="670" alt="Screen Shot 2019-07-02 at 13 18 57" src="https://user-images.githubusercontent.com/343259/60508909-f5f0bd80-9ccb-11e9-8f3a-0ecc5a9a9612.png">

**Comment by moyogo** [comment]
There’s no reason I can think of why t should not be in the same column as s in table 7-1 of the Unicode standard 12.0.
Romanian text data using both tcedilla and scedilla would have them with comma below but now there’s tcommaaccent and scommaaccent. Gagauz text data would have them with the same diacritics, most likely a cedilla. Makanya orthography has them both with the cedilla, and Manjaku uses t with cedilla as well.
The 1972 UN Romanization of Arabic and the 1967 UN Romanization of Persian used them with cedilla.

**Comment by lianghai** [comment]
@moyogo: I think that s vs t thing might be a typo. Would you like to thoroughly review the concerning sections (mostly on page 290 and 291) then submit some feedback?

**Comment by moyogo** [comment]
@lianghai I’ll write some feedback.
