### ISSUE TITLE
`legacy:` prefix for Arabic presentation form names?

### ISSUE THREAD

**Issue by LettError** [LettError/glyphNameFormatter#56]
The GNUFL names of the Arabic presentation form names cause confusion. For instance, a variant of the glyph `seen` with unicode `0633`, `seen.init` should not have any unicode value. But GNUFL suggests `FEB3`. 

So, if the presentation form unicodes (all of them? some of them?) are only for legacy support, then what about adding a `legacy:` prefix to these names for disambiguation. This should happen in the presentation form rangeprocessors (https://github.com/LettError/glyphNameFormatter/blob/master/Lib/glyphNameFormatter/rangeProcessors/arabic_presentation_forms_a.py)

**Comment by twardoch** [comment]
Generally, these glyphs should be in fonts and be accessible through OpenType Layout features. In addition, they may have the Unicode codepoints from the presentation block. Most font vendors will include the codepoints, as they're not PUA. I'd keep this data as is. It'd be silly to suggest to people to include two identical glyphs: seen.init (accessible through the init feature) and legacy:seen.init (with the presentational mapping)

**Comment by LettError** [comment]
Yes, that's more or less what I've been told :) Ok, there is goes. Thanks @twardoch!

**Comment by twardoch** [comment]
I’ll just add for the sake of completeness: 

The problem of Arabic Presentational forms is not so hugely different (it is a bit different, but no so much) from the problem that many precomposed Latin letters exist in Unicode, like `Aacute` (Á U+00C1). 

Without legacy, Unicode would unambiguously encode them as U+0041 U+0301 and the font would compose the Á on the fly, either through a `ccmp` substitution or through `mark` placement. Then, U+00C1 and hundreds of other such combinations would not be needed in the Unicode standard at all. But there are some benefits of them being there — the presence of Unicode precomposed or presentational codepoints passes certain knowledge to users and type designers. 

The repertoire of the Arabic precomposed letters that are in Unicode give the layman some clue about the overall glyph repertoire needed in an Arabic font. Unicode gives only a minimal set, but it does give it. 

The fact that these forms can be accessed via multiple methods (the direct presentational codepoint or the `init`, `fina`, `medi`, `isol` features) is somewhat secondary — and again, somewhat similar to how Á can be accessed in multiple ways (either by U+00C1 or by U+0041 U+0301 plus `ccmp` or `mark`).

**Comment by twardoch** [comment]
BTW, the “only” debatable issue for glyphs with Arabic presentational Unicodes is the formation of the final production glyphnames. 

* We may have the glyph `seen` which would have the codepoint U+0633 and which would get the final glyphname `uni0633`. That’s pretty clear. 
* We may also have the glyph `seen.init` which in most cases would get the codepoint U+FEB3, and it would also be mapped in the `init` feature via `sub seen by seen.init;`. The open question is whether the final glyphname for the glyph should be `uniFE63` or `uni0633.init`. I’ve seen fonts done either way. The glyphname `uniFE63` is “more legacy” while the glyphname `uni0633.init` is “more modern”. 

@LettError Is the question of forming final production glyphnames “in-scope” or “out-of-scope” for this very project (glyphNameFormatter and GNUFL)?

**Comment by LettError** [comment]
I suppose final production names would "just" be another list to generate. If the name is different from the GNUFL name there can be code that adjusts. But at the moment I don't have any resources to add this.
