### ISSUE TITLE
greek not complete

### ISSUE THREAD

**Issue by typemytype** [LettError/glyphNameFormatter#58]
there are duplicates in the `latin-extended-d` that dont get a nice prefix/suffix

```
   392 : Beta                                              Beta                     Beta                                    Greek and Coptic                        GREEK CAPITAL LETTER BETA
  A7B4 : Beta                                              -                        Beta                                    Latin Extended-D                        LATIN CAPITAL LETTER BETA
```

its seems like no latin will get a prefix...

see https://github.com/LettError/glyphNameFormatter/blob/master/Lib/glyphNameFormatter/__init__.py#L190

see 

https://github.com/LettError/glyphNameFormatter/blob/master/Lib/glyphNameFormatter/names/glyphNamesToUnicode.txt#L888

https://github.com/LettError/glyphNameFormatter/blob/master/Lib/glyphNameFormatter/names/glyphNamesToUnicode.txt#L7669

**Comment by LettError** [comment]
Most latin names do not want the script prefix. I added a boss-level override.

**Comment by LettError** [comment]
Fixed.
