### ISSUE TITLE
0269 iotalenis vs. 1F30 iotalenis

### ISSUE THREAD

**Issue by LettError** [LettError/glyphNameFormatter#6]
`        037A           iotalenis       iotasubscript        gr-iotalenis                        Greek and Coptic`
`        1F30           iotalenis           iotalenis        gr-iotalenis                          Greek Extended`

**Comment by typemytype** [comment]
`037A Greek and Coptic GREEK YPOGEGRAMMENI`
AGD: `iotasubscript` 
char:  ͺ

`1F30  Greek Extended GREEK SMALL LETTER IOTA WITH PSILI`
AGD: `iotalenis` 
char:  ἰ

**Comment by typemytype** [comment]
changed it to follow the AGD list like: `iotasubscript` (see commit https://github.com/LettError/glyphNameFormatter/commit/72cf2ae48e94a58b199f0272df5079d264e87557)

could also be set as `iotalenissubscript` or just `ypogegrammeni`
