### ISSUE TITLE
Confusing inconsistency in Devanagari names

### ISSUE THREAD

**Issue by lianghai** [LettError/glyphNameFormatter#83]
So… What is the intention behind squeezing `vocal` in between the core part and `sign` but leave other modifier words to trail otherwise? And why is `signelongcandra` such a special beast?

https://github.com/LettError/glyphNameFormatter/blob/f7439b4b2699b7ed61a38829b5d449dbdcce8360/Lib/glyphNameFormatter/rangeProcessors/devanagari.py#L6-L14

https://github.com/LettError/glyphNameFormatter/blob/f7439b4b2699b7ed61a38829b5d449dbdcce8360/Lib/glyphNameFormatter/names/glyphNamesToUnicode.txt#L1826-L1844

**Comment by lianghai** [comment]
Just a note here for future reference, about the background of the decision making for `vocalicrsign` (was `rvocalsign` before), etc:

- The name part `VOCALIC` is not frequently used enough and well understood enough to be abbreviated.
- Average users of these glyph names would expect to see `VOCALIC R/RR/L/LL` (or _vocalic liquid_) characters sorted together on their own, not sorted next to `RA` and and `LA` characters (and also `RRA` and `LLA` consonant letters are completely unrelated), therefore `VOCALIC` is not made a suffix. (Although I personally like the idea of trying to get rid of the distinction between vowels and consonants.)
- The change was made to `helper_indic.py` intentionally to cover Indic scripts generally, because this is a Sanskrit phonology thing and is shared by all Indic scripts.

**Comment by LettError** [comment]
@lianghai thank you so much! Did you have a look at the names as they generate now?

**Comment by lianghai** [comment]
@LettError The intended changes look good. Will need to fully review other names later.

(Reopening this issue as I just realized the commits are not in the master yet.)

**Comment by LettError** [comment]
Considering all these changes are not really in the right issue anyway, I suggest I merge this branch and then we can open a new one for any indic corrections.

**Comment by typemytype** [comment]
+1 for margin the current state of the "Georgian support" branch. To many different changes already in there.
