### ISSUE TITLE
Update for Unicode 12.1.0

### ISSUE THREAD

**Issue by lianghai** [LettError/glyphNameFormatter#84]
Include the new stuff from:

http://www.unicode.org/versions/Unicode12.0.0/ (the major update)
http://www.unicode.org/versions/Unicode12.1.0/ (a minor update with a single new character)

Fyi, as I participated the standardization process of almost all of the 12.0/12.1 new characters, it’ll be relatively easy for me to review new characters’ names.

Also this will give me an opportunity to really look into this project!

**Comment by LettError** [comment]
I processed the names with a new list from 12.1.0. I didn't check any of the new names or ranges though.
