### ISSUE TITLE
Great! :)

### ISSUE THREAD

**Issue by twardoch** [LettError/glyphNameFormatter#9]
Hi Erik, 

So you were doing something rather useful when publishing your sarcastic tweets about Unicode character names. Now I understand! :) 

As it happens, I've been trying to do some work in that field recently as well. For a number of mathematical characters, there is a good source of sensible names which we could lift from the `unicode.xml` file in the https://github.com/w3c/xml-entities repo, which is an official W3C-maintained list of short names for character entities. 

This is the human-readable version of that document: 
https://www.w3.org/2003/entities/2007doc/bycodes.html
but the `unicode.xml` file also contains many names from other namespaces, especially from the [TeX unicode-math](https://github.com/wspr/unicode-math/blob/master/unicode-math-table.tex) documents which catalogs names as used by various LaTeX packages. 

The XML entity list and the unicode-math list aren’t completely identical, but potentially one of those is a good source for standardized, well-thought-out shorter list for many characters (mostly symbols). Some characters are the same in both lists, for example U+2AAC (⪬) is called `smte` in both lists. But for example U+1D49C (𝒜) is called `mscrA` in unicode-math and `Ascr` in the XML Entity list. 

Would you say that it might make sense to adopt at least some of these? They seem pretty systematic.

**Comment by LettError** [comment]
Thank you I will have a look. At first glance the names in the xml-entities list appear rather cryptic.

**Comment by twardoch** [comment]
The ones in [unicode-math](https://github.com/wspr/unicode-math/blob/master/unicode-math-table.tex) are generally decent, I think. Perhaps not all. But they do have a sensible system for those bold italic sanserifs that you so love ;) And they’re actually in so far useful that they’re really used by the TeX community. Perhaps at least those prepended with the "MATHEMATICAL" in their UCD name could be given a prefix `math-` (or `math:` or whatever).

**Comment by twardoch** [comment]
Ps. I’ll be happy to "curate" this. BTW, since https://github.com/w3c/xml-entities in `unicode.xml` is maintaining mappings to 3rd-party names (currently mostly from the TeX world), once your list stabilizes, W3C could pull our names and include them in `unicode.xml` under a separate attribute inside `unicode.xml`. 

Please let me know how I can help in this effort. I’ll be most happy to contribute in any way I can.
