### ISSUE TITLE
reader.u2n issue: strange behaviour

### ISSUE THREAD

**Issue by RafalBuchner** [LettError/glyphNameFormatter#90]
well, this is a mystery:

one of the people that I work with had this output

```File "/Applications/RoboFont.app/Contents/Resources/lib/python3.7/glyphNameFormatter/reader.py", line 89, in u2n
    if isIdeograph(value):
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.7/glyphNameFormatter/reader.py", line 57, in isIdeograph
    if a<=value<=b:
TypeError: '<=' not supported between instances of 'int' and 'NoneType'
```

I used glyphNameFormatter in the RF script that changes glyph names based on their Unicode, using u2n. This script worked on every other computer but mentioned fella's laptop. I tested it with the same ufos etc.

I fixed it by making a custom glyphNameFormatter version, where u2n function looked like this:
```Python
def u2n(value):
	"""Unicode value to glyphname"""
	global uni2name
	v = uni2name.get(value)
	if v is not None:
		return v
        # I added two lines below to make sure 
        # that u2n returns None if the value is None:
	else:
		return None
	if isIdeograph(value):
		return uniPatternName(value)
```

any idea what was going on? 
Before I made this small fix, I made some tests to find what could cause the problem.
We tried to uninstalling RF, its custom libraries, all extensions and scripts to make sure that nothing in RF's environment 'special' is influencing the behavior of this library. Then we installed a fresh RF and run the script on the same computer. The same output appeared. Any ideas about what could go wrong?

 (RF's embedded version of glyphNameFormatter was 0.4, but the same happened if we installed the last version as an external library). Also, the same happened on few different RF builds.

Cheers

**Comment by LettError** [comment]
* This commit should at least prevent the original traceback from happening. 
* Otherwise I don't know why you get different results on different machines. 
* Might have to wait before this version gets picked up by the next RF4b.
