### ISSUE TITLE
Faulty name for “and with dot”

### ISSUE THREAD

**Issue by arialcrime** [LettError/glyphNameFormatter#94]
While going through the glyph names of a font, I came across a strange suggested unicode value for a glyph called “dot”. 
Turns out n2u was suggesting the unicode for “and with dot”.

### To replicate:
```python
from glyphNameFormatter.reader import n2u

name = 'dot'
v = n2u(name)

print(name, hex(v), chr(v), u2r(v))
```
Output:
`dot 0x27d1 ⟑ Miscellaneous Mathematical Symbols-A`

**Comment by LettError** [comment]
Fixed: 
```>>> from glyphNameFormatter.reader import *
>>> print(u2n(0x27d1))
andwithdot
>>> print(n2u("dot"))
None
```

**Comment by LettError** [comment]
Thank you @arialcrime!
